### DISCUSSION TITLE
How to FastBoot device via Labgrid as infrastructure

### DISCUSSION THREAD

**Discussion by AmanRavan** [labgrid-project/labgrid#1093] [Q&A]
I have written the exporter.yaml 

```yaml
resources:
  my_device:
    driver: android
    bindings:
      usb:
        vid: 0x1234
        pid: 0x5678
    capabilities:
      fastboot:
        enabled: true
```

After running the command
`(labgrid-venv) debian@RajajiRaspi $ labgrid-client -p placeName fastboot locationOfImageFile.img`

But I am getting the below error 
```
labgrid-client: error: unknown resource class my_device
This is likely caused by an error in the environment configuration or invalid
resource information provided by the coordinator.
```

Any suggestion how to resolve it ?

Note - I have connected by device to exporter and with Fastboot mode ON.
