### DISCUSSION TITLE
Remote Access from pytest with tags

### DISCUSSION THREAD

**Discussion by graugans** [labgrid-project/labgrid#1244] [Q&A] [answered]
With the labgrid-client I have added tags to a place like this:

```
labgrid-client  --place M04239-1 set-tags article=M04239
```

On the command line I can aquire the place based on the tags, I assume in case multipüle places provide the same tags I get a free one.

```
labgrid-client reserve article=M04239
```

With the token I can aquire the place

```
labgrid-client  --place +OB0489VDKJ acquire
```

But how can this be achieved from a pytest environment. From the [Environment Configuration](https://labgrid.readthedocs.io/en/latest/configuration.html#environment-configuration) docs I have figured out there is the possibility to use environment variables:

```yaml
targets:
  main:
    resources:
      RemotePlace:
        name: !template $LG_PLACE
tools:
  qemu_bin: !template "$BASE/bin/qemu-bin"
```

But how can I get the place to be put into `LG_PLACE`?

**Comment by Bastian-Krause** [comment, marked as answer]
With your configuration, this should be possible via `export LG_PLACE=+`:
```shell
$ eval `labgrid-client reserve --shell board=imx6`
$ labgrid-client wait $LG_TOKEN
owner: erbse/bst
token: L7KN0X2UUG
state: allocated
filters:
  main: board=imx6
allocations:
  main: example
created: 2023-07-21 12:44:02.284611
timeout: 2023-07-21 12:45:04.489250
$ export LG_PLACE=+
$ labgrid-client lock
acquired place example
$ pytest --lg-env=conf.yaml test_barebox.py
```

See also https://labgrid.readthedocs.io/en/latest/usage.html#place-scheduling

**Reply by graugans** [reply]
Perfect, the complete example:

### The `conf.yaml` file
```yaml
targets:
  main:
    resources:
      RemotePlace:
        name: !template $LG_PLACE
```

### The`test_network.py`  file

```python
import pytest

@pytest.fixture()
def ovp8xx(target):
    return target.get_resource('NetworkService')

def test_something(ovp8xx):
    address = ovp8xx.address
    assert address == "192.168.0.69"
```

## The exporter `configuration.yaml` file

```yaml
test-rack-M04239:
  USBSerialPort:
    match:
      '@ID_PATH': pci-0000:00:14.0-usb-0:7.2:1.0
    speed: 115200
  NetworkService:
    address: 172.25.125.66
    username: root
    password: 'xxxxxxxxxxxxxxxxxxxxxxxx'
  PDUDaemonPort:
    host: mybox.intra.ifm
    pdu: pico-relay
    index: 1
```

I kind of missuse labgrid here as an resource management for my CI/CD hardware infrastructure. For now I mainly use this for network based application testing. The lowlevel on device testing will follow. I may also add some strategy here to ensure the IP is set correct and the device is available over the network.

The neat thing here is that I can have multiple targets and have a locking and retreaval of the IP address for free.
