### DISCUSSION TITLE
remote resources, place scheduling, pytest, putting it all together

### DISCUSSION THREAD

**Discussion by cruise-bryan-murdock** [labgrid-project/labgrid#1248] [Q&A]
I have multiple remote resources, organized into places.  I can tag the places so that a given test can find a place to run.  If my test environment yaml looks like this:
```
targets:
  main:
    resources:
      RemotePlace:
        name: !template LG_PLACE
    drivers:
        ...
```
Then I can do this:
```
eval "$(clg reserve --shell --wait board_type=foo)"
export LG_PLACE=+
clg -p + lock
pytest --lg-env=target.yaml
clg -p + unlock
```

If I have multiple tests that all can run on the same place, the above still works.  I can even create a script that does all that, so a user can just type one command instead of all those.

If I have multiple different tests, some of which require one board type and some which require another board type, then it gets trickier.  Here is what I have come up with so far.  A single test environment that looks like this:
```
targets:
  target_foo:
    resources:
      RemotePlace:
        name: !template LG_FOO_PLACE
    drivers:
        ...
  target_bar:
    resources:
      RemotePlace:
        name: !template LG_BAR_PLACE
    drivers:
        ...
```
Then a custom fixtures for using those targets in tests.  Here's the target_foo fixture:
```
@pytest.fixture(scope="session")
def target_foo(env):
    """Return the target 'foo' configured in the supplied configuration file."""
    target = env.get_target("foo")
    if target is None:
        print("ERROR: target foo not found in the environment yaml")
        sys.exit(1)
    return target
```
And here is my script:
```
eval "$(clg reserve --shell --wait board_type=foo)"
LG_EPP_PLACE=$(clg -p + lock | sed 's/acquired place //g')
export LG_FOO_PLACE

eval "$(clg reserve --shell --wait board_type=bar)"
LG_PCIE_PLACE=$(clg -p + lock | sed 's/acquired place //g')
export LG_BAR_PLACE

pytest --lg-env=targets.yaml

for PLACE in $(env | grep 'LG_.*_PLACE' | sed 's/=.*//'); do
    clg -p "${!PLACE}" unlock
done
```
This is ok for running multiple tests, but if you are just running one foo test and run the above script you'll lock a bar place that you don't need.  So I'd need a separate script or scripts for running individual tests.  Which is getting painful to write and maintain.  So I'm curious if anyone has any ideas on how to do this in a better and/or simpler way.
