### DISCUSSION TITLE
Using multiple serial drivers from yaml environment

### DISCUSSION THREAD

**Discussion by mitchellostler** [labgrid-project/labgrid#1259] [Q&A]
For our labgrid configuration, we are running tests and hoping to use two serial connections on a remote lab host. 
We would like to be able to run shell commands via the ShellDriver on each of these serial ports. 
Our configuration is specified in our environment yaml file:
```yaml
targets:
  resources:
    RemotePlace: 
      name: remote1
  drivers:
    SerialDriver:
      name: 's1'
    SerialDriver:
      name: 's2'
    ...
```

Reading through the documentation, it seems that labgrid supports multiple drivers with the same type, via the name parameter, and the `target.get_driver('SerialDriver', name=name)` method can be used to get them individually. 

However, it is not stated how the underlying resources should be configured. We currently export two USBSerialPort resources with different paths from our RemotePlace, but when our Target is initialized, the second SerialDriver overwrites the first. We could also initialize these drivers in our code, as opposed to our yaml file, but there doesn't seem to be a way to distinguish between the resources they are using. 

What should the configuration be to access two serial drivers on different ports from the same project?

**Comment by Emantor** [comment]
This is unfortunately not very clear from the documentation, but each driver supports a `bindings` attribute where the name bindings can be specified. This means that for a `RemotePlace` with two serial ports named i.e. `default` and `second`, the driver configuration would look like this:
```yaml
targets:
  resources:
    RemotePlace: 
      name: remote1
  drivers:
    SerialDriver:
      name: 's1'
      bindings:
        port: default
    SerialDriver:
      name: 's2'
      bindings:
        port: second
```

Where the named `SerialDriver` `s1` now binds to the `SerialPort` `default` and `SerialDriver` `s2` binds to the port `second`. To create the explicit names for the `RemotePlace`, `add-named-match` needs to be used instead of `add-match`.

My example already contains a recent change to labgrid, namely that if `labgrid-client -p remote1 console` is called, labgrid will use the port named default by default, instead of requiring an explicit name. If the other port is required, it can still be passed explicitly.

Futher information for binding and driver activation is available inside the docs [here](https://labgrid.readthedocs.io/en/latest/overview.html#binding-and-activation).

**Reply by yianchen-2023** [reply]
Hi Emantor,

I followed your comment and used "add-named-match" to add two named NetworkSerialPort. But, the target.get_driver(‘SerialDriver’, name=name) still could not find the first named SerialDriver in the project yaml file.

We have labgrid version 23.0.3

The resource “show" command output looks as follows:
```
matches:
    L711/L711/NetworkSerialPort/a_uart -> a_uart
    L711/L711/NetworkSerialPort/b_uart -> b_uart
  acquired: None
  acquired resources:
  created: 2023-08-23 15:47:20.114902
  changed: 2023-08-23 15:49:50.730250
Matching resource 'a_uart' (L711/L711/NetworkSerialPort/a_uart):
  {'acquired': None,
   'avail': True,
   'cls': 'NetworkSerialPort',
   'params': {'extra': {'path': '/dev/ttyUSB3',
                        'proxy': 'l711',
                        'proxy_required': True},
              'host': 'L711',
              'port': None,
              'speed': 115200}}
Matching resource ‘b_uart' (L711/L711/NetworkSerialPort/b_uart):
  {'acquired': None,
   'avail': True,
   'cls': 'NetworkSerialPort',
   'params': {'extra': {'path': '/dev/ttyUSB2',
                        'proxy': 'l711',
                        'proxy_required': True},
              'host': 'L711',
              'port': None,
              'speed': 115200}}
```

My project yaml file looks as follows:
```yaml
      SerialDriver:
	name: ‘a_uart_driver'
        bindings:
	  port: ‘a_uart'
      SerialDriver:
	name: ‘b_uart_driver'
        bindings:
	  port: ‘b_uart’
```

**Reply by Bastian-Krause** [reply]
@Emantor's configuration is incorrect. You need to specify the drivers as a yaml list, not as a yaml dictionary (the second SerialDriver would overwrite the first, due to duplicate keys). See the documentation about [Environment configuration](https://labgrid.readthedocs.io/en/latest/configuration.html#environment-configuration). It contains an example with multiple SerialDrivers.

**Reply by yianchen-2023** [reply]
@Bastian-Krause: Thanks for your help.

I am following up on the configuration discussion for using one project YAML file for two serial port configurations.

I did some more experiments.

Labgrid accepts the project YAML file as follows (only for experiment purposes)

```yaml
targets:
  main:
    resources:
    - RawSerialPort:
        name: 'ca55_uart'
        port: '/dev/ttys001'
    - RawSerialPort:
        name: 'cr5_uart'
        port: '/dev/ttys002'
    drivers:
    - SerialDriver:
        name: 'ca55_uart_driver'
        bindings:
          port: 'ca55_uart'
    - SerialDriver:
        name: 'cr5_uart_driver'
        bindings:
          port: 'cr5_uart'
```

However, Labgrid would not take it if I add a ShellDriver entry in the file (it doesn’t matter if it is a list type or dictionary type): 

```yaml
targets:
  main:
    resources:
    - RawSerialPort:
        name: 'ca55_uart'
        port: '/dev/ttys001'
    - RawSerialPort:
        name: 'cr5_uart'
        port: '/dev/ttys002'
    drivers:
    - SerialDriver:
        name: 'ca55_uart_driver'
        bindings:
          port: 'ca55_uart'
    - SerialDriver:
        name: 'cr5_uart_driver'
        bindings:
          port: ‘cr5_uart'	
      ShellDriver:
        prompt: '# '
        login_prompt: ' login: '
        username: 'root'
        login_timeout: 30
```

———————
NOTE: Labgrid doesn’t seem to take the list type of ShellDriver entry either, as follows
```yaml
     - ShellDriver:
        prompt: '# '
        login_prompt: ' login: '
        username: 'root'
        login_timeout: 30
```

My questions are as follows (Please correct me if I did not ask the right questions): 

For project YAML:
1) How can I extend the list to include more drivers in the project YAML for both resources and drivers?
2)  As to ShellDriver, do you think there's a need to bind it to a specific serial port?
3) While using YAML list to specify drivers, do I always need to use YAML list to specify the resources partially or all?

For exporter yaml
1) If yes, for the (3) in project YAML, do we need to export remote resources as a YAML list in the exporter config? Since our remote resources are all exported via labgrid exporter as follows, it doesn't seem to work with the YAML list in the project YAML’s drivers section (NOTE: I used add-named-match to add the resources to L711 one by one, and resource show command was in my previous post last week)

**Project YAML**
```yaml
    resources:
      RemotePlace:
        name: L711
    drivers:
    - SerialDriver:
        name: 'ca55_uart_driver'
        bindings:
          port: 'ca55_uart'
    - SerialDriver:
        name: 'cr5_uart_driver'
        bindings:
          port: 'cr5_uart'
```

**Exporter YAML file**
```yaml
L711:
  location: lab
  ca55_uart:
    cls: USBSerialPort
    match:
      ID_SERIAL_SHORT: FT4XSQFX
  cr5_uart:
    cls: USBSerialPort
    match:
      ID_SERIAL_SHORT: FT55R8PX

  < some other resources>
```

Please let me know and correct me if there are any missing setups on the exporter or project side.

**Reply by yianchen-2023** [reply]
Sorry, somehow the format of YAML was changed after clicking on the reply.

**Comment by cruise-bryan-murdock** [comment]
I think the real question we have is just this.  If this is our exporter config:
```
SFO3-HIL-LT-711:
  location: sunnyvale-lab
  ca55_uart:
    cls: USBSerialPort
    match:
      ID_SERIAL_SHORT: FT4XSQFX
  cr5_uart:
    cls: USBSerialPort
    match:
      ID_SERIAL_SHORT: FT55R8PX
```
And our place is:
```
Place 'lt711_test':
  matches:
    SFO3-HIL-LT-711/SFO3-HIL-LT-711/NetworkSerialPort/ca55_uart -> ca55_uart
    SFO3-HIL-LT-711/SFO3-HIL-LT-711/NetworkSerialPort/cr5_uart -> cr5_uart
```
And our test target yaml is:
```
targets:
  main:
    resources:
      RemotePlace:
        name: lt711_user
    drivers:
    - SerialDriver:
        name: 'ca55_uart_driver'
        bindings:
          port: 'ca55_uart'
    - SerialDriver:
        name: 'cr5_uart_driver'
        bindings:
          port: 'cr5_uart'
    - APCDriver: {}
    - LauterbachDriver: {}
    - ShellDriver:
        console: 'ca55_uart_driver'
        prompt: '# '
        login_prompt: ' buildroot login: '
        username: 'root'
        login_timeout: 30
```
The `console` line isn't working how I think it should.  I just get this error:
```
abgrid.exceptions.NoDriverFoundError: multiple drivers matching <class 'labgrid.protocol.consoleprotocol.ConsoleProtocol'> found in Target(name='main', env=Environment(config_file='ca55-working.yaml')) with the same priorities
```
How do we bind the ShellDriver to the ca55_uart_driver?

**Reply by sestebanz** [reply]
You can achieve what you want using the "bindings" tag again in the ShellDriver:
```
- ShellDriver:
  bindings:
    console: 'ca55_uart_driver'
  prompt: '# '
  login_prompt: ' buildroot login: '
  username: 'root'
  login_timeout: 30

**Reply by cruise-bryan-murdock** [reply]
Thank you @sestebanz , that works for the ShellDriver, and for our custom drivers.  It's not working for our custom strategy that closely follows the examples of other labgrid strategies, I get the same "multiple drivers matching" even though I have this:
```
    - LinuxBootStrategy:
        bindings:
          console: 'ca55_uart_driver'
```
I'm noticing that drivers have this:
```
class ShellDriver(CommandMixin, Driver, CommandProtocol, FileTransferProtocol):
    bindings = {"console": ConsoleProtocol, }
```
But strategies have this:
```
class BareboxStrategy(Strategy):
    """BareboxStrategy - Strategy to switch to barebox or shell"""
    bindings = {
        "power": "PowerProtocol",
        "console": "ConsoleProtocol",
        "barebox": "BareboxDriver",
        "shell": "ShellDriver",
    }
```
Does the quoting of "ConsoleProtocol" make some difference?

**Reply by cruise-bryan-murdock** [reply]
After much stepping through the labgrid code, I figured it out.  The Strategy has both a console and a serial binding that are needed.  This is the target yaml that works for the strategy now:
```
    - LinuxBootStrategy:
        bindings:
          console: 'ca55_uart_driver'
          serial: 'ca55_uart_driver'
```
It would sure be nice if the error messages from labgrid made this more clear!

**Reply by Bastian-Krause** [reply]
Could you please provide a way to reproduce the error message that should be improved?

**Reply by cruise-bryan-murdock** [reply]
I guess to reproduce it you'd need a target env that has two SerialDrivers, and a driver or strategy that binds to a serial protocol.  Then make sure you don't add `bindings` for the driver or strategy.  You should get an error message like this:
```
ERROR ss_cr5_test.py::test_ss - labgrid.exceptions.NoDriverFoundError: multiple drivers matching <class 'labgrid.driver.serialdriver.SerialDriver'> found in Target(name='main', env=Environment(config_file='ca55-working.yaml')) with ...
```
It would be nice if it told me **_which_** driver or strategy is looking for the SerialDriver.

Knowing what to look for now, I can see the strategy in the middle of the big traceback that is shown before the above message, but that was not obvious to me when first looking at this.

**Reply by Bastian-Krause** [reply]
See #1270 for improved target error messages.

**Reply by cruise-bryan-murdock** [reply]
That looks like it will much more helpful, thanks!

**Comment by rpoisel** [comment]
Maybe it is of help to someone here. I have created a sample self-contained labgrid setup based on docker compose that uses two serial ports. There is just one `ShellDriver`, but it should give an idea how to bind it to one of the available serial ports.

Repository: https://github.com/honeytreelabs/labgrid-compose-sample

Note: the `usbserial-id` parameters in the exporter configuration have to be changed to your needs.

**Comment by RosyDev** [comment]
I am also trying to configure different `SerialPortDriver` and `HttpDigitalOutputDriver` in an `env.yaml` file and bind them in a strategy.

My attempt with only the serials looks like this:
**env.yaml:**

```yaml
targets:
  main:
    resources:
      RemotePlace:
        name: 'ex1-dut1'

    drivers:       
      SerialDriver:
        name: 'dbg_console'
        bindings:
          port: 'dbg'    
      SerialDriver:
        name: 'tty_console'
        bindings:
          port: 'tty'

      DemoStrategy: {}

imports:
  - demo-strategy.py
```

**demo_strategy.py:**

```import enum
import attr
from labgrid.step import step
from labgrid.strategy import Strategy, StrategyError
from labgrid.factory import target_factory
from labgrid.protocol import ConsoleProtocol

class Status(enum.Enum):
    unknown = 0
    on = 1
    off = 2

@target_factory.reg_driver
@attr.s(eq=False)
class DemoStrategy(Strategy): 
    """DemoStrategy - Strategy to interact with the tty and the dbg console""" 
    bindings = {
        "tty_console": "ConsoleProtocol",
        "dbg_console": "ConsoleProtocol",
    }

    status = attr.ib(default=Status.unknown)

    def __attrs_post_init__(self):
        super().__attrs_post_init__()

    @step(args=['status'])
    def transition(self, status, *, step):  # pylint: disable=redefined-outer-name
        if not isinstance(status, Status):
            status = Status[status]
        if status == Status.unknown:
            raise StrategyError(f"Cannot transition to {status}")
        elif status == self.status:
            step.skip("Nothing to do")
            return  # Nothing to do
        elif status == Status.on:
            self.target.activate(self.tty_console)
            self.target.activate(self.dbg_console)
        elif status == Status.off:
            self.target.deactivate(self.tty_console)
            self.target.deactivate(self.dbg_console)
        else:
            raise StrategyError(f"No transition found from {self.status} to {status}")
        
        self.status = status
```

I get the following error:

```/usr/local/lib/python3.11/dist-packages/labgrid/util/yaml.py:26: UserWarning: /client-conf/demo.yaml: previous entry with duplicate YAML dictionary key 'SerialDriver' overwritten
  warnings.warn(
Selected role main and place ex1-dut1 from configuration file
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/labgrid/remote/client.py", line 2106, in main
    target = session._get_target(place)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/labgrid/remote/client.py", line 797, in _get_target
    target = self.env.get_target(self.role)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/labgrid/environment.py", line 49, in get_target
    target = target_factory.make_target(role, config, env=self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/labgrid/factory.py", line 159, in make_target
    self.make_driver(target, driver, name, args)
  File "/usr/local/lib/python3.11/dist-packages/labgrid/factory.py", line 138, in make_driver
    d = cls(target, name, **args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<attrs generated init demo-strategy.DemoStrategy>", line 8, in __init__
    self.__attrs_post_init__()
  File "/client-conf/demo-strategy.py", line 25, in __attrs_post_init__
    super().__attrs_post_init__()
  File "/usr/local/lib/python3.11/dist-packages/labgrid/strategy/common.py", line 28, in __attrs_post_init__
    super().__attrs_post_init__()
  File "/usr/local/lib/python3.11/dist-packages/labgrid/driver/common.py", line 25, in __attrs_post_init__
    super().__attrs_post_init__()
  File "/usr/local/lib/python3.11/dist-packages/labgrid/binding.py", line 55, in __attrs_post_init__
    target.bind(self)
  File "/usr/local/lib/python3.11/dist-packages/labgrid/target.py", line 430, in bind
    return self.bind_driver(bindable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/labgrid/target.py", line 389, in bind_driver
    raise BindingError(
labgrid.binding.BindingError: duplicate bindings of SerialDriver(main) to dbg_console for <class 'labgrid.protocol.consoleprotocol.ConsoleProtocol'> found in target Target(name='main', env=Environment(config_file='/client-conf/demo.yaml'))
```

If I only use the following binding:
```bindings = {
    "tty_console": "ConsoleProtocol",
}
```

or

```bindings = {
    "dbg_console": "ConsoleProtocol",
}
```

it works.

As soon as I try to bind the HttpGpios, nothing works anymore.

Can anyone help me with this?
