### DISCUSSION TITLE
How do I define a YEPKIT ykush device?

### DISCUSSION THREAD

**Discussion by sjg20** [labgrid-project/labgrid#1349] [Q&A] [answered]
I am not sure how to use a ykusb device 
I have added this to my exporter yaml:

```
rpi3:
  YKUSHPowerPort:
    serial: 'YK17698'
    index: 1
```

when I try to control it:

LG_CROSSBAR=ws://kea/ws labgrid-client -p rpi3 power on 
labgrid-client: error: target has no compatible resource available

The documentation doesn't really explain how the magic is supposed to work. Does anyone have a full example?

**Comment by Emantor** [comment]
The relevant part is described [here](https://labgrid.readthedocs.io/en/latest/getting_started.html#client) in the documentation. The exporter configuration registers your resource with the distributed infrastructure (your exporter configuration is missing a group though). This resource should be shown via `labgrid-client resources` and than you can assemble a place `labgrid-client -p <place> create` and add resource matches `labgrid-client add-match`. `labgrid-client -p <placename> show` will show the current configuration of the place.

The reasoning behind this complexity is that resources can be arranged in a rack or on a shelf and you can dynamically assign resources (serial ports, power switches,…) as hardware is added and removed.

**Reply by sjg20** [reply]
Thanks for the info. I thought I was doing that, but probably not correctly. I updated the above to show the group. Here is the output from the commands you mention:

```
LG_CROSSBAR=ws://kea/ws labgrid-client -p rpi3 r
kea/rpi3/NetworkUSBSDWireDevice
kea/rpi3/NetworkSerialPort
kea/rpi3/YKUSHPowerPort
(=6f283 crossbar-kea.yaml crossbar-requirements.txt first_test/) sglass@ELLESMERE /vid/software/devel/ubtest/lab> LG_CROSSBAR=ws://kea/ws labgrid-client -p rpi3 -v r
Exporter 'kea':
  Group 'rpi3' (kea/rpi3/*):
    Resource 'USBSDWireDevice' (kea/rpi3/NetworkUSBSDWireDevice[/USBSDWireDevice]):
      {'acquired': 'rpi3',
       'avail': True,
       'cls': 'NetworkUSBSDWireDevice',
       'params': {'busnum': 1,
                  'control_serial': 'sdwire-18',
                  'devnum': 12,
                  'extra': {'proxy': 'kea', 'proxy_required': False},
                  'host': 'kea',
                  'model_id': 24577,
                  'path': '/dev/sdo',
                  'vendor_id': 1256}}
    Resource 'USBSerialPort' (kea/rpi3/NetworkSerialPort[/USBSerialPort]):
      {'acquired': 'rpi3',
       'avail': True,
       'cls': 'NetworkSerialPort',
       'params': {'extra': {'path': '/dev/ttyUSB16',
                            'proxy': 'kea',
                            'proxy_required': False},
                  'host': 'kea',
                  'port': 38835,
                  'speed': 115200}}
    Resource 'YKUSHPowerPort' (kea/rpi3/YKUSHPowerPort[/YKUSHPowerPort]):
      {'acquired': 'rpi3',
       'avail': True,
       'cls': 'YKUSHPowerPort',
       'params': {'extra': {'proxy': 'kea', 'proxy_required': False},
                  'index': 1,
                  'serial': 'YK17698'}}
(=6f283 crossbar-kea.yaml crossbar-requirements.txt first_test/) sglass@ELLESMERE /vid/software/devel/ubtest/lab> LG_CROSSBAR=ws://kea/ws labgrid-client -p rpi3 show
Place 'rpi3':
  matches:
    kea/rpi3/NetworkSerialPort
    kea/rpi3/NetworkUSBSDWireDevice
    kea/rpi3/YKUSHPowerPort
  acquired: ellesmere/sglass
  acquired resources:
    kea/rpi3/NetworkSerialPort/USBSerialPort
    kea/rpi3/NetworkUSBSDWireDevice/USBSDWireDevice
    kea/rpi3/YKUSHPowerPort/YKUSHPowerPort
  created: 2024-04-08 14:21:05.573051
  changed: 2024-04-08 15:00:46.261703
Acquired resource 'USBSerialPort' (kea/rpi3/NetworkSerialPort/USBSerialPort):
  {'acquired': 'rpi3',
   'avail': True,
   'cls': 'NetworkSerialPort',
   'params': {'extra': {'path': '/dev/ttyUSB16',
                        'proxy': 'kea',
                        'proxy_required': False},
              'host': 'kea',
              'port': 38835,
              'speed': 115200}}
Acquired resource 'USBSDWireDevice' (kea/rpi3/NetworkUSBSDWireDevice/USBSDWireDevice):
  {'acquired': 'rpi3',
   'avail': True,
   'cls': 'NetworkUSBSDWireDevice',
   'params': {'busnum': 1,
              'control_serial': 'sdwire-18',
              'devnum': 12,
              'extra': {'proxy': 'kea', 'proxy_required': False},
              'host': 'kea',
              'model_id': 24577,
              'path': '/dev/sdo',
              'vendor_id': 1256}}
Acquired resource 'YKUSHPowerPort' (kea/rpi3/YKUSHPowerPort/YKUSHPowerPort):
  {'acquired': 'rpi3',
   'avail': True,
   'cls': 'YKUSHPowerPort',
   'params': {'extra': {'proxy': 'kea', 'proxy_required': False},
              'index': 1,
              'serial': 'YK17698'}}
```

My full exporter file is:

```
rpi3:
  location: 'USB hub C'
  USBSerialPort:
    ## usbhubc-port4
    match:
      '@ID_PATH': 'pci-0000:03:00.2-usb-0:5.2.4:1.0'

  USBSDWireDevice:
    ## usbhubc-port9
    match:
      ## '@ID_PATH': 'pci-0000:03:00.2-usb-0:5.4.1.2'
      'ID_SERIAL_SHORT': 'sdwire-18'

  YKUSHPowerPort:
    ## usbhubc-hubc14
    ## match:
    ##  '@ID_PATH': pci-0000:03:00.2-usb-0:5.1.2:1.0
    serial: 'YK17698'
    index: 1
```

**Reply by Emantor** [reply]
I think you are using the latest release (v23.0.5), but support for YKushPowerPort devices has not made it into a release yet. I am currently writing the release notes for a new release. I also pushed a `v24.0a1` tag, the action should publish an alpha release to pypi which you can use test whether it works on master.

**Reply by sjg20** [reply]
I am using 'pip install  .'  with this commit:

722838b (HEAD -> fred, origin/master, origin/HEAD) Merge pull request #1348 from Bastian-Krause/bst/network-test-simplification

**Reply by Emantor** [reply]
Hm, the code to handle conversion from a local YKUSHPowerPort to a NetworkYKUSHPowerPort seems to be missing.
You can fix this up locally for now by using NetworkYKUSHPowerPort and specifying the host attribute explicitly.

Edit:
The code is there, what looks wrong is this line:
```
kea/rpi3/YKUSHPowerPort/YKUSHPowerPort
```
this should be:
```
kea/rpi3/NetworkYKUSHPowerPort/YKUSHPowerPort
```

**Reply by sjg20** [reply]
Thanks for the info. I am not able to change the 'labgrid-client r' output to what you have here. I have tried this:

```
rpi3:
...
  NetworkYKUSHPowerPort:
    ## usbhubc-hubc14
    ## match:
    ##  '@ID_PATH': pci-0000:03:00.2-usb-0:5.1.2:1.0
    host: kea
    serial: 'YK17698'
    index: 1
```

If there is code missing to handle the conversion, would it be easier for me to add that? Is there test coverage for this feature?
