### DISCUSSION TITLE
ser2net: Setting break failed

### DISCUSSION THREAD

**Discussion by abeezarburhan** [labgrid-project/labgrid#1439] [General]
Hi

I have an odroindN2 board. I have flashed the sd card using the sd mux - ubuntu 22.-4 ( Login/password: root/ubuntu).
I have the serial port connector. 
I am able to connect to serial port using minicom however I have a failure when wheing `labgrid-client -p <PLACE> console`

Error Message:

labgrid-exporter:
```
ser2net[1009910]: serialdev: Setting break failed on /dev/ttyUSB0, try adding the nobreak option
```
labgrid-client:
```
(labgrid-venv) dir_labgrid$ labgrid-client -p <PLACE> console
connecting to NetworkSerialPort(target=Target(name='example-place-1', env=None), name='USBSerialPort', state=<BindingState.bound: 1>, avail=True, host='myhost', port=45173, speed=115200, protocol='rfc2217') calling microcom -s 115200 -t myhost:45173
connected to 127.0.1.1 (port 45173)
Escape character: Ctrl-\
Type the escape character to get to the prompt.
exiting
(labgrid-venv) dir_labgrid$
```

conf.yaml:
```yaml
example-group-1:
  location: "my_desk_1"
  USBSerialPort:
    match:
      ID_PATH: pci-0000:00:14.0-usb-0:3:1.0
    speed: 115200
  USBSDWireDevice:
    match:
      ID_PATH: pci-0000:00:14.0-usb-0:4.2
```

I am not sure if I need to update the Shell driver to be able to match the prompt/login/password.

Any pointers appreciated
