### DISCUSSION TITLE
Need help for setting up UUUDriver

### DISCUSSION THREAD

**Discussion by mibers** [labgrid-project/labgrid#1453] [Q&A] [answered]
Hi there,

I'm QA Engineer and quite new to Embedded systems.
I started using GitLab and my current goal is to flash 
an image to an IMX8MP EVK. Setup as follows:

**DUT:** IMX8MP EVK
**exporter:** raspberry pi "pi-exporter" running docker container
**coordinator:** raspberry pi "pi-coordinator" running docker container
**client:** raspberry pi "pi-client" running on raspberry OS.

uuu is installed on the exporter and works when run from CLI:
```
 sudo ./uuu -b emmc_all $HOME/imx-boot-fmc $HOME/epitos-qt6-fmc.wic.zst
```

Environment:
===========
```
targets:
  raspberry_pi:
    resources:
      RemotePlace:
        name: raspberry-place
    drivers:
      - SSHDriver:
          keyfile: "~/.ssh/id_rsa"   # Path to your SSH key file if using key-based authentication, leave empty if using password
  evk:
    resources:
      RemotePlace:
        name: evk-place
    drivers:
      - SSHDriver:
          keyfile: "~/.ssh/id_rsa"   # Path to your SSH key file if using key-based authentication, leave empty if using password
      - UUUDriver:
          image: bootloade_image
          script: emcc_all
  sot:
    resources:
      RemotePlace:
        name: sot-place
    drivers:
      - SSHDriver:
          keyfile: "~/.ssh/id_rsa"   # Path to your SSH key file if using key-based authentication, leave empty if using password
images:
  bootloade_image: ~/imx-boot-fmc
tools:
  uuu-loader: ~/mfgtools/uuu
```
Exporter conf:
=============
```
sot-group:
  NetworkService:
    address: 192.168.169.191
    port: 22
    username: root
    password: ""
evk-group:
  location: evk-exporter
  NetworkService:
    address: 192.168.150.240
    port: 22
    username: root
    password: ""
  NetworkSerialPort:
    host: 192.168.150.65
    port: 53866
  IMXUSBLoader:
    match:
      ID_PATH: pci-0000:00:01.0-usb-0:1.3
```
Test script:
===========
```
def test_flash_with_uuu(env):
    print("Start flashing with uuu!")
    print("env.targets: ", env.targets)
    target = env.get_target("evk")
    print("target: ", target)

    uuu_driver = target.get_driver('UUUDriver')

    target.activate(uuu_driver)
```
I know thats incomplete but the issue seems to be my config.

When i run command
```
python -m pytest ~/labgrid/client/simple-test/uuu_flash_test.py --lg-env ~/labgrid/client/simple-test/remote.yaml
```

I get:
```
home/pi/labgrid-os/labgrid/venv/bin/python -m pytest /home/pi/labgrid/client/simple-test/uuu_flash_test.py --lg-env /home/pi/labgrid/client/simple-test/remote.yaml 
============================= test session starts ==============================
platform linux -- Python 3.11.2, pytest-7.2.2, pluggy-1.5.0
rootdir: /home/pi
plugins: labgrid-24.0a2.dev88
collected 1 item                                                               

../../labgrid/client/simple-test/uuu_flash_test.py F                     [100%]

=================================== FAILURES ===================================
_____________________________ test_flash_with_uuu ______________________________

env = Environment(config_file='/home/pi/labgrid/client/simple-test/remote.yaml')

    def test_flash_with_uuu(env):
        print("Start flashing with uuu!")
        print("env.targets: ", env.targets)
        target = env.get_target("evk")
        print("target: ", target)
    
>       uuu_driver = target.get_driver('UUUDriver')

../../labgrid/client/simple-test/uuu_flash_test.py:7: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
labgrid/target.py:234: in get_driver
    return self._get_driver(cls, name=name, resource=resource, activate=activate)
labgrid/target.py:208: in _get_driver
    self.activate(found[0])
labgrid/target.py:462: in activate
    self.await_resources(resources)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Target(name='evk', env=Environment(config_file='/home/pi/labgrid/client/simple-test/remote.yaml'))
resources = [NetworkIMXUSBLoader(target=Target(name='evk', env=Environment(config_file='/home/pi/labgrid/client/simple-test/remote...1>, avail=False, host='pi-exporter', timeout=10.0, busnum=None, devnum=None, path=None, vendor_id=None, model_id=None)]
timeout = Timeout(timeout=10.0), avail = True

    def await_resources(self, resources, timeout=None, avail=True):
        """
        Poll the given resources and wait until they are (un-)available.
    
        Args:
            resources (List): the resources to poll
            timeout (float): optional timeout
            avail (bool): optionally wait until the resources are unavailable with avail=False
        """
        self.update_resources()
    
        waiting = set(r for r in resources if r.avail != avail)
        static = set(r for r in waiting if r.get_managed_parent() is None)
        if static:
            raise NoResourceFoundError(
                f"Static resources are not {'available' if avail else 'unavailable'}: {static}"
            )
    
        if not waiting:
            return
    
        if timeout is None:
            timeout = Timeout(max(resource.get_managed_parent().timeout for resource in waiting))
        else:
            timeout = Timeout(timeout)
    
        while waiting and not timeout.expired:
            waiting = set(r for r in waiting if r.avail != avail)
            for r in waiting:
                r.poll()
            if not any(r for r in waiting if r.avail == avail):
                # sleep if no progress
                sleep(0.5)
    
        if waiting:
>           raise NoResourceFoundError(
                f"Not all resources are {'available' if avail else 'unavailable'}: {waiting}",
                filter=waiting
            )
E           labgrid.exceptions.NoResourceFoundError: Not all resources are available: {NetworkIMXUSBLoader(target=Target(name='evk', env=Environment(config_file='/home/pi/labgrid/client/simple-test/remote.yaml')), name='IMXUSBLoader', state=<BindingState.bound: 1>, avail=False, host='pi-exporter', timeout=10.0, busnum=None, devnum=None, path=None, vendor_id=None, model_id=None)}

labgrid/target.py:100: NoResourceFoundError
----------------------------- Captured stdout call -----------------------------
Start flashing with uuu!
env.targets:  {'raspberry_pi': Target(name='raspberry_pi', env=Environment(config_file='/home/pi/labgrid/client/simple-test/remote.yaml')), 'evk': Target(name='evk', env=Environment(config_file='/home/pi/labgrid/client/simple-test/remote.yaml')), 'sot': Target(name='sot', env=Environment(config_file='/home/pi/labgrid/client/simple-test/remote.yaml'))}
target:  Target(name='evk', env=Environment(config_file='/home/pi/labgrid/client/simple-test/remote.yaml'))
=========================== short test summary info ============================
FAILED ../../labgrid/client/simple-test/uuu_flash_test.py::test_flash_with_uuu - labgrid.exceptions.NoResourceFoundError: Not all resources are available: {...
============================== 1 failed in 10.88s ==============================

Process finished with exit code 1
```

What's missing or screwed up in my config and why I see "NetworkIMXUSBLoader" in the error?
Pls. advice how to properly configure UUUDriver. I checked all the official documentation as well as 
the issues on GitHub but didn't succeed with my task yet.

Thx a lot,
Martin

P.S: The rather odd looking config is a result of lots or "trial an errors".

**Comment by Emantor** [comment]
How do you forward `udev` events and devices from outside the docker container into the docker container running the exporter?

**Reply by mibers** [reply]
I use docker compose and my config looks like this:
```
version: '3.3'
services:
  exporter:
    image: "labgrid-exporter"
    environment:
      - LG_CROSSBAR=ws://${COORDINATOR_IP}:${COORDINATOR_PORT}/ws
    network_mode: "host"
    volumes:
      - "/home/pi/labgrid/dockerfiles/staging/exporter-conf:/opt/conf"
      - "/run/udev:/run/udev:ro"
    command: bash -c "set -e &&
      /opt/wait-for-it/wait-for-it.sh ${COORDINATOR_IP}:${COORDINATOR_PORT} -- labgrid-exporter /opt/conf/exporter.yaml"
    restart: always
  ser2net:
   image: ghcr.io/jippi/docker-ser2net
   network_mode: "host"
   volumes:
     - "/home/pi/labgrid/dockerfiles/staging/exporter-conf/ser2net.yaml:/etc/ser2net/ser2net.yaml"
   devices:
     - "/dev/ttyUSB2:/dev/ttyUSB2"
   restart: always
```
