### DISCUSSION TITLE
Flash 2 images together with UUUDriver to iMX8MP EVK board

### DISCUSSION THREAD

**Discussion by mibers** [labgrid-project/labgrid#1462] [Q&A]
Hi all,

I managed to flash the bootloader to an iMX8MP EVK board 
using UUUDriver. This under the hood executes

```
sudo ./uuu -b emmc_all $HOME/imx-boot-fmc
```

but we usually flash our boards with bootloader and
a .wic image. On the shell running uuu it looks like this:

```
sudo ./uuu -b emmc_all $HOME/imx-boot-fmc $HOME/epitos-qt6-fmc.wic.zst
```

Is there any chance to achieve the same using labgrids UUUDriver?
Running uuu a second time like

```
sudo ./uuu -b emmc_all $HOME/epitos-qt6-fmc.wic.zst
```

didn't work. Also attempts adding several images to the environment didn't work.
This issue relates to https://github.com/labgrid-project/labgrid/discussions/1453

Config as:

Environment:
===========
```
targets:
  raspberry_pi:
    resources:
      RemotePlace:
        name: raspberry-place
    drivers:
      - SSHDriver:
          keyfile: "~/.ssh/id_rsa"   # Path to your SSH key file if using key-based authentication, leave empty if using password
  evk:
    resources:
      RemotePlace:
        name: evk-place
    drivers:
      - SSHDriver:
          keyfile: "~/.ssh/id_rsa"   # Path to your SSH key file if using key-based authentication, leave empty if using password
      - UUUDriver:
          image: bootloade_image
          script: emcc_all
  sot:
    resources:
      RemotePlace:
        name: sot-place
    drivers:
      - SSHDriver:
          keyfile: "~/.ssh/id_rsa"   # Path to your SSH key file if using key-based authentication, leave empty if using password
images:
  bootloade_image: ~/imx-boot-fmc
tools:
  uuu-loader: ~/mfgtools/uuu
```
Exporter conf:
=============
```
sot-group:
  NetworkService:
    address: 192.168.169.191
    port: 22
    username: root
    password: ""
evk-group:
  location: evk-exporter
  NetworkService:
    address: 192.168.150.240
    port: 22
    username: root
    password: ""
  NetworkSerialPort:
    host: 192.168.150.65
    port: 53866
  IMXUSBLoader:
    match:
      ID_PATH: pci-0000:00:01.0-usb-0:1.3
```

Thanks and best regards,
Martin
