### DISCUSSION TITLE
QEMUDriver is killing the QEMU process when using the "power on" command

### DISCUSSION THREAD

**Discussion by LukeHackwell** [labgrid-project/labgrid#1471] [Q&A] [answered]
Hi!

I'm trying to get a setup working for the QEMUDriver. 

I am using this guide as a base for my QEMU config - [Boot ARM64 virtual machines on QEMU](https://ubuntu.com/server/docs/boot-arm64-virtual-machines-on-qemu). I'm able to run this outside of Labgrid with no issues.

Here's my config for the QEMUDriver, based on to the guide above:
```
targets:
  main:
    resources:
      RemotePlace:
        name: my_board
    drivers:
      QEMUDriver:
        qemu_bin: 'qemu-system-aarch64'
        machine: 'virt'
        cpu: 'max'
        memory: '4G'
        extra_args: '-drive if=pflash,format=raw,file=efi.img,readonly=on -drive if=pflash,format=raw,file=varstore.img -drive if=none,file=ubuntu-24.04-server-cloudimg-arm64.img,id=hd0 -drive file=user-data.img,format=raw -device virtio-blk-device,drive=hd0 -netdev type=tap,id=net0 -device virtio-net-device,netdev=net0'
```

When I run `labgrid-client -c qemu.config power on`, I get the following error:
`qemu-system-aarch64: terminating on signal 15 from pid <PID> (<PYTHON PATH>)`

After debugging this, it seems that Labgrid is executing the `QEMUDriver.on` method which brings up the QEMU process. However, once it has finished it exits and triggers the `QEMUDriver._atexit` method, which kills the QEMU process, causing QEMU to print the error above.

I also get the same error when I run an "empty config":
```
targets:
  main:
    resources:
      RemotePlace:
        name: my_board
    drivers:
      QEMUDriver:
        qemu_bin: 'qemu-system-x86_64'
        machine: 'q35'
        cpu: 'max'
        memory: '4G'
        extra_args: ''
```
In this case I'd also expect the QEMU process to stay up

Any help is much appreciated.

Thanks!
