### DISCUSSION TITLE
Accessing a remote network interface on an exporter

### DISCUSSION THREAD

**Discussion by colin-foster-in-advantage** [labgrid-project/labgrid#1513] [Q&A]
I'm reading the documentation and it isn't clear to me whether what I'm trying to do is possible. I'd like to access a remote Ethernet port on my Labgrid Exporter (Raspberry Pi) from my local PC.

## Setup 1 - Local Ethernet

This configuration currently works for me

```
----------------------- 10.1.1.1                    10.1.1.3 -------------
|         PC          | -------------------------------------|    DUT    |
|      Labgrid        |                                      |           |
|       Client        |                                      |           |
|                     |     WiFi          ------------       |           |
|                     | - - - - - - - - - |   RPi    |=======|           |
|                     |    192.168.1.x    | Exporter |       |           |
-----------------------                   ------------       -------------
```

From this setup, I'm able to run `pytest` on my PC (without `--lg-env`) and Labgrid is a way to access the remote serial port and power switch.

What I'm really looking for is this:

## Setup 2 - Remote Ethernet

```
-----------------------                                      -------------
|         PC          |                                      |    DUT    |
|      Labgrid        |                                      |           |
|       Client        |                                      |           |
|                     |     WiFi          ------------       |           |
|                     | - - - - - - - - - |   RPi    |=======|           |
|                     |    192.168.1.x    | Exporter |-------|           |
-----------------------                   ------------       -------------
                                             10.1.1.2         10.1.1.3
```

I have configured the RPi to export `eth0`

```
vsc-group:                                                          
  location: colins-vsc                                              
  USBSerialPort:                                                    
    match:                                                          
      ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0
  NetworkInterface:                                                 
    ifname: 'eth0'                                                  
```

And the resource shows up

```
(venv) $ labgrid-client -p vsc show
Place 'vsc':
  matches:
    */vsc-group/*
  acquired: colin
  acquired resources:
    lg-vsc/vsc-group/NetworkSerialPort/USBSerialPort
    lg-vsc/vsc-group/RemoteNetworkInterface/NetworkInterface
  created: 2024-06-10 14:53:02.073546
  changed: 2024-08-22 13:55:16.733584
Acquired resource 'USBSerialPort' (lg-vsc/vsc-group/NetworkSerialPort/USBSerialPort):
  {'acquired': 'vsc',
   'avail': True,
   'cls': 'NetworkSerialPort',
   'params': {'extra': {'path': '/dev/ttyUSB0',
                        'proxy': 'lg-vsc',
                        'proxy_required': False},
              'host': 'lg-vsc',
              'port': 38813,
              'speed': 115200}}
Acquired resource 'NetworkInterface' (lg-vsc/vsc-group/RemoteNetworkInterface/NetworkInterface):
  {'acquired': 'vsc',
   'avail': True,
   'cls': 'RemoteNetworkInterface',
   'params': {'extra': {'proxy': 'lg-vsc', 'proxy_required': False},
              'host': 'lg-vsc',
              'ifname': 'eth0'}}
```

I don't understand what I can do with the remote network interface. Do I need to create an SSH proxy? Is this a resource that is only available via `pytest --lg-env`?
