### DISCUSSION TITLE
Struggling with multiple serial ports

### DISCUSSION THREAD

**Discussion by ArmadilloChubbz** [labgrid-project/labgrid#1594] [Q&A]
Hi,

Just started giving labgrid a go, so please excuse my ignorance...

I'm trying to get multiple USB serial ports (a quad FTDI UART chip) to work remotely. I've tried various configurations but am just stabbing in the dark at this point.

This is my exporter file
```
pi-on-desk:
  console-a:
    cls: 'USBSerialPort'
    match:
      ID_PATH: platform-xhci-hcd.1-usb-0:1:1.0

  console-b:
    cls: 'USBSerialPort'
    match:
      ID_PATH: platform-xhci-hcd.1-usb-0:1:1.1

  console-c:
    cls: 'USBSerialPort'
    match:
      ID_PATH: platform-xhci-hcd.1-usb-0:1:1.2
```

That is exported and coordinator and client seems to work okay.

On my remote machine I want to do something like:

```
targets:
  main:
    resources:
      RemotePlace:
        name: !template '$LG_PLACE'

    drivers:
      - SerialDriver
        name: "console-a"

      - SerialDriver
        name: "console-b"
        
      - SerialDriver
        name: "console-c"
        
      - ShellDriver
        name: "console-a"
        prompt: ""
        login_prompt: ""
        username: ""

      - ShellDriver
        name: "console-b"
        prompt: ""
        login_prompt: ""
        username: ""

      - ShellDriver
        name: "console-c"
        prompt: ""
        login_prompt: ""
        username: ""
```

Any help would be appreciated, thanks

**Comment by joergho** [comment]
Hi @ArmadilloChubbz ,

this should work:

```yaml
targets:
  main:
    resources:
      RemotePlace:
        name: !template '$LG_PLACE'

    drivers:
      - SerialDriver
        name: "console-a"
        bindings:
            port: "console-a"

      - SerialDriver
        name: "console-b"
        bindings:
            port: "console-c"
        
      - SerialDriver
        name: "console-c"
        bindings:
            port: "console-c"
        
      - ShellDriver
        name: "shell-a"
        bindings:
            console: "console-a"
        prompt: ""
        login_prompt: ""
        username: ""

      - ShellDriver
        name: "shell-b"
        bindings:
            console: "console-a"
        prompt: ""
        login_prompt: ""
        username: ""

      - ShellDriver
        name: "shell-c"
        bindings:
            console: "console-c"
        prompt: ""
        login_prompt: ""
        username: ""
```
