### DISCUSSION TITLE
SSH interface binding

### DISCUSSION THREAD

**Discussion by DiogoSilva014** [labgrid-project/labgrid#1618] [Q&A]
Hi,

I need some help regarding the setup that I am trying to achieve.
```
                                         ----------> DUT 1
Client < -------- > Exporter < -------- |
                                         ----------> DUT 2

``` 
I need to access both DUT 1 and DUT 2 via SSH. Both these DUT's are connected to different network interfaces, but have the same IP address. Is there any implemented way to solve this problem?

Currently my exporter looks like this:
``` 
    SSH:
         cls: 'NetworkService'
         address: '10.100.30.160'
         username: 'root'
         password: 'blablabla123'
```
I would need to add another device with the same address.

I saw in the documentation that there is the possibility of adding the '%' character to specify the interface, but reading the code I didn't get the impression that this was what I needed.

Also, currently I specify a proxy when using labgrid-client.

Best regards,
Diogo
