### ISSUE TITLE
Multiple NetworkService and labgrid.yaml

### ISSUE THREAD

**Issue by kjeldflarup** [labgrid-project/labgrid#1049]
I have started to use the 0.4.x series after upgrading from 0.1.x, one of the reasons to upgrade is the possibility to have multiple network services in my exporter. 

```yaml
  ssh:
    cls: NetworkService
    address: '192.168.7.193'
    username: 'root'
    password: 'xxxx'
  pi:
    cls: NetworkService
    address: '192.168.7.10'
    username: 'pi'
    password: 'xxxx'
```
Now I found that if I have set `LG_ENV="/etc/labgrid.yaml"`  
and in labgrid.yaml has this
```yaml
      SSHDriver:
        keyfile: !template $LG_KEYFILE
```
Then I get this error 
```
+ labgrid-client -p pcm33_192_pi015 scp --name ssh artifacts/AMC300_pcm33_CODESYS3.5.18.30_v1.3.0.6-local-50-ge0c53e50-dirty.raucb :/tmp/pcm.raucb
Selected role main from configuration file
labgrid-client: error: multiple resources matching <class 'labgrid.resource.networkservice.NetworkService'> found in Target(name='main', env=Environment(config_file='/etc/labgrid.yaml'))
Found multiple resources but no name was given, available names:
pi
ssh
```
It is not the keyfile that is the problem, it seems to be the existence of `SSHDriver` in `labgrid.yaml`

Does the SSHDriver need to have two distinct sections, and how to do that?

**Comment by Emantor** [comment]
How does your place configuration look like?

**Comment by kjeldflarup** [comment]
This is actually what I suspect, that SSHDriver does not know which NetworkService to use

The full exporter looks like this:
```
pcm33_193:
  location: pcm33_193
  USBSerialPort:
    match:
      '@sys_name': '1-1.3:1.3'
  NetworkPowerPort:
    model: simplerest
    host: 'http://$LG_EXPORTERIP:9999/gpio/18/{value}'
    index: 0
  ssh:
    cls: NetworkService
    address: '192.168.7.193'
    username: 'root'
    password: 'xxxx'
  pi:
    cls: NetworkService
    address: '$LG_EXPORTERIP'
    username: 'pi'
    password: 'xxxx'
```
And the labgrid.yaml looks like this
```
imports:
  - deif.labgrid.strategy
targets:
  main:
    resources:
      RemotePlace:
        name: !template $LG_PLACE
    drivers:
      NetworkPowerDriver:
        delay: 3.0
      SerialDriver:
        txdelay: 0.01
      ShellDriver:
        prompt: '~ # '
        login_prompt: ' login: '
        username: 'root'
        password: 'deif7800'
        login_timeout: 45
        keyfile: !template $LG_KEYFILEPUB
      SSHDriver:
        keyfile: !template $LG_KEYFILE
      UBootDriver:
        prompt: '=> '
      DbootUBootStrategy: {}
```

**Comment by Bastian-Krause** [comment]
Yep, you need a SSHDriver per NetworkService:

```yaml
imports:
  - deif.labgrid.strategy
targets:
  main:
    resources:
      RemotePlace:
        name: !template $LG_PLACE
    drivers:
    - NetworkPowerDriver:
        delay: 3.0
    - SerialDriver:
        txdelay: 0.01
    - ShellDriver:
        prompt: '~ # '
        login_prompt: ' login: '
        username: 'root'
        password: 'deif7800'
        login_timeout: 45
        keyfile: !template $LG_KEYFILEPUB
    - SSHDriver:
        keyfile: !template $LG_KEYFILE
        bindings:
          networkservice: ssh
    - SSHDriver:
        keyfile: !template $LG_KEYFILE
        bindings:
          networkservice: pi
    - UBootDriver:
        prompt: '=> '
    - DbootUBootStrategy: {}
```
