### ISSUE TITLE
Using multiple serial drivers from yaml environment 

### ISSUE THREAD

**Issue by mitchellostler** [labgrid-project/labgrid#1258]
For our labgrid configuration, we are running tests and hoping to use two serial connections on a remote lab host. 
We would like to be able to run shell commands via the ShellDriver on each of these serial ports. 
Our configuration is specified in our environment yaml file:
```
targets:
  resources:
    RemotePlace: 
      name: remote1
  drivers:
    SerialDriver:
      name: 's1'
    SerialDriver:
      name: 's2'
    ...
```

Reading through the documentation, it seems that labgrid supports multiple drivers with the same type, via the name parameter, and the `target.get_driver('SerialDriver', name=name)` method can be used to get them individually. 

However, it is not stated how the underlying resources should be configured. We currently export two USBSerialPort resources with different paths from our RemotePlace, but when our Target is initialized, the second SerialDriver overwrites the first. We could also initialize these drivers in our code, as opposed to our yaml file, but there doesn't seem to be a way to distinguish between the resources they are using. 

What should the configuration be to access two serial drivers on different ports from the same project?
