### ISSUE TITLE
test_shell script returns [Errno13] Permission denied when trying to access serial port

### ISSUE THREAD

**Issue by gcsam11** [labgrid-project/labgrid#1333]
I'm connected through SSH to a Raspberry Pi 4 where the serial port are registered as /dev/ttyX (using 0). The user is already in groups tty and dialout and it's also important to note that while trying sudo lsof /dev/tty0 i get error `lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs 
Output information may be incomplete.`
This is my local.yaml file: 
```yaml
targets:
  main:
    resources:
      RawSerialPort:
        port: "/dev/tty0"
    drivers:
      ManualPowerDriver:
        name: "example"
      SerialDriver: {}
      ShellDriver:
        prompt: 'gonca@\w+:[^ ]+ ' # also tried this with root
        login_prompt: 'login: '
        username: 'gonca' 
        password: '-----'
```
