### ISSUE TITLE
Command-line option to statically configure places

### ISSUE THREAD

**Issue by sjg20** [labgrid-project/labgrid#1358]
See #1069 (but I was unable to reopen it, so created a new issue with more details)

The current approach requires these steps when starting up the lab:

crossbar start --config ../cfg/crossbar-kea.yaml
LG_CROSSBAR=ws://kea:20408/ws labgrid-exporter ../cfg/export_kea.yaml
LG_CROSSBAR=ws://kea:20408/ws ../labgrid/contrib/sync-places.py sync cfg/places_kea.yaml

It would be better to have labgrid-exporter handle the sync automatically, e.g. by loading the places file.

But even better to not have a places file. My export_kea.yaml file looks like this:

```
rpi3:
  location: 'USB hub C'
  USBSerialPort:
    ## usbhubc-port4
    match:
      '@ID_PATH': 'pci-0000:03:00.2-usb-0:5.2.4:1.0'

  USBSDWireDevice:
    ## usbhubc-port9
    match:
      ## '@ID_PATH': 'pci-0000:03:00.2-usb-0:5.4.1.2'
      'ID_SERIAL_SHORT': 'sdwire-18'

  YKUSHPowerPort:
    serial: 'YK17698'
    index: 1
```

and places_kea.yaml is just:
```
places:
  rpi3:
    matches:
      - kea/rpi3/*
```
which seems pretty redundant to me.

So could we perhaps have an option to create a place for each exported target as a place?

Yes, I am aware that most uses of labgrid create ad-hoc labs consisting of one or two targets. But I have a lab of about 34 targets so far, so ad-hoc creation isn't really practical.
