### ISSUE TITLE
Add list and dict to MapValue

### ISSUE THREAD

**Issue by cidlik** [labgrid-project/labgrid#1485]
Hello!

**Problem**
I would add a new functionality to my fork (and yours project too if it likes you). It's SoC bootmode switching. Every SoCs have a specific count of bootmodes, thus I cannot list them into resource's attributes. Pins, which control bootmode, may be connected to relay switches. I think that i can realize structure in `resources.yaml`:

```YAML
  bootmode:
    cls: RelayBootMode
    model: rodos
    host: 127.0.0.1
    description:
      indexes: [2, 3, 4]
      mode0: [0, 0, 0]
      mode3: [0, 1, 1]
      mode7: [1, 1, 1]
```
but I cannot do this because `labgrid/remote/common.py::set_map_from_dict()` doesn't allow to use dictionaries and lists.
I saw in `labgrid/remote/proto/labgrid-coordinator.proto` a comment:
```
message MapValue {
  oneof kind {
    ...
    // FIXME do we need arrays?
  }
};
```
I thought that it is a use case when arrays and dictionaries may be used.

**Questions**
* Is this a right way to declare resources? Is it satisfy to your vision of the project?
* Can you support lists and dictionaries for attribute value?

Best regards,
cidlik

P.S. TY for your project, it's realy cool.
