### ISSUE TITLE
!template syntax isn't supported for NetworkService.port

### ISSUE THREAD

**Issue by jordan-bonser** [labgrid-project/labgrid#1576]
I've been attempting to use the environment yaml config to pass in the NetworkService port value, like so:

```yaml
targets:
  main:
    resources:
      NetworkService:
        address: !template "$LG_NETWORK_ADDRESS"
        username: !template "$LG_NETWORK_USERNAME"
        password: !template "$LG_NETWORK_PASSWORD"
        port: !template "$LG_NETWORK_PORT"
```

Unfortunately this fails the attrs int validator as currently the !template functionality uses environment variables which are inherently strings.

In `PDUDaemonPort` for the index there has been the addition of an attrs converter:

```python
@target_factory.reg_resource
@attr.s(eq=False)
class PDUDaemonPort(Resource):
    """The PDUDaemonPort describes a port on a PDU accessible via PDUDaemon

    Args:
        host (str): name of the host running the PDUDaemon
        pdu (str): name of the PDU in the configuration file
        index (int): index of the power port on the PDU
    """
    host = attr.ib(validator=attr.validators.instance_of(str))
    pdu = attr.ib(validator=attr.validators.instance_of(str))
    index = attr.ib(validator=attr.validators.instance_of(int), converter=int)
```

I believe adding this to the NetworkService Resource would mean the !template functionality would work for the NetworkService.port which would be ideal for our usecase.
