### ISSUE TITLE
YKUSHPowerPort via coordinator fails

### ISSUE THREAD

**Issue by tgbloks** [labgrid-project/labgrid#161]
H

i just tried to run my tests (using the new YKUSHPowerDriver) via the exporter / coordinator over network (the actual setup uses 3 different docker containers for coordinator, exporter and client where only the exporter has USB access) and it does not work - looks like the client is trying to access USB locally.
(YKUSHPowerDriver complains about not being able to access the USB port on the HW)
Should that work or did i miss to implement something?
here my configuration:
exporter:

```
foo:
  location: bar
  NetworkService:
    address: "10.10.10.10"
    username: "root"
  YKUSHPowerPort:
    serial: "serial"
    index: 1
```
client:
```
targets:
  main:
    resources:
      RemotePlace:
        name: "dev1"
    drivers:
      YKUSHPowerDriver: {}
      SSHDriver:
        keyfile: "./id_rsa"
      BloksStrategy: {}
```
