### ISSUE TITLE
Automatically match for port in USBSerialPort

### ISSUE THREAD

**Issue by andreasdotzler** [labgrid-project/labgrid#268]
On a system with multiple usb serial ports a configuration for a USBSerialPort with explicit port configured matches to the first available port. For example on a system with /dev/ttyUSB0 and /dev/ttyUSB1, the following config 
```
  USBSerialPort:
    port: /dev/ttyUSB1
    speed: 115200
```
will falsely match to /dev/ttyUSB0.

The correct result is achieved by explicitly configuring a match
```
  USBSerialPort:
    port: /dev/ttyUSB1
    speed: 115200
    match:
      'DEVNAME': '/dev/ttyUSB1'
```
unfortunately this is not intuitive to the inexperienced user.

I suggest to automatically add this match to USBSerialPort if a port is configured, something like

```
class USBSerialPort(USBResource, SerialPort):
    def __attrs_post_init__(self):
        if self.port is not None:
            self.match['DEVNAME'] = self.port
        self.match['SUBSYSTEM'] = 'tty'
        super().__attrs_post_init__()
```
