### ISSUE TITLE
A `login_optional: false` property to force ShellDriver to expect login_prompt first

### ISSUE THREAD

**Issue by a3f** [labgrid-project/labgrid#296]
I am writing a test that should probe for a successful login which looks like this:

```
Welcome to Buildroot
buildroot login: root
#
```

I added `login_prompt: 'login: '` and `prompt: '# '` to my YAML:
```
targets:
  main:
    resources:
      - RemotePlace:
          name: 'birne-rechts'
    drivers:
      - SerialDriver: {}
      - NetworkPowerDriver:
          delay: 5.0
      - ShellDriver:
          login_timeout: 30
          login_prompt: 'login: '
          prompt: '# '
          username: 'root'
      - loginStrategy: {}
```

But `# ` matches beforehand while in U-Boot:

```
## Flattened Device Tree blob at 21000000^M
```

Because, helpfully, the `ShellDriver` doesn't mind matching a shell `prompt` even when `login_prompt` has yet to to arrive:

https://github.com/labgrid-project/labgrid/blob/8af10923f3f44495d425904c28b90021be02eb9e/labgrid/driver/shelldriver.py#L108

https://github.com/labgrid-project/labgrid/blob/8af10923f3f44495d425904c28b90021be02eb9e/labgrid/driver/shelldriver.py#L120-L128

Specifying `prompt: '\n# '` is a work around, but making this configurable via a `login_optional:` property would be nice.

I also wonder if a `re.MULTILINE` regex where `^` and `$` match start and end of line respectively wouldn't be the better default.

(Cc: @BastianStender @strumtrar who helped with debugging)
