### ISSUE TITLE
IMXUSBDriver not loading SPL

### ISSUE THREAD

**Issue by chtavares** [labgrid-project/labgrid#425]
Hello, 

I'm trying to use labgrid to bootsrap my device. 

I'm using the following local.yaml file:

```
targets:
  main:
    resources:
      IMXUSBLoader:
        match:
          'sys_name': '1-3'
    drivers:
      ManualPowerDriver:
        name: '1-3'
      IMXUSBDriver:
        image: image-spl
tools:
  imx-usb-loader: imx_usb_loader/imx_usb
images:
  image-spl: SPL
```
and with this tests.py file :
```
def test_usb(target):
    r = target.get_resource('IMXUSBLoader')
    assert r.devnum is not None
    assert r.busnum is not None

def test_imx_load(target):
    bp = target.get_driver('BootstrapProtocol')
    bp.load()

```
Using this, all tests pass, however, the SPL image is not loaded on my device. How can I debug this issue?
