### ISSUE TITLE
Cannot login to board

### ISSUE THREAD

**Issue by nandra** [labgrid-project/labgrid#559]
I'm using labgrid to test presence of accelerometer on my board.
Test is simple just check if path exists and then reboot board.

my yaml looks like:
```
targets:
  main:
    resources:
      RawSerialPort:
        port: "/dev/ttyUSB0"
    drivers:
      ManualPowerDriver:
        name: "example"
      SerialDriver: {}
      ShellDriver:
        prompt: 'root@MYCAM-1234:~#'
        login_prompt: ' login: '
        username: 'root'
        password: ''
```

and debug log shows:
```
Labgrid Console Logfile for main
Logfile started at 2020-01-14 10:13:37.078249
=== Log starts here ===


Poky (Yocto Project Reference Distro) 2.4.4 MYCAM-1234 ttyAMA0

MYCAM-1234 login:

Poky (Yocto Project Reference Distro) 2.4.4 MYCAM-1234 ttyAMA0

MYCAM-1234 login:

```

also trace is pushed to here: https://pastebin.com/6Ur1tdfd

Any ideas why it cannot login to board? I suspect again some regexp issue but cannot spotted it by myself. Thanks.
