### ISSUE TITLE
How to let uboot driver print device log realtime?

### ISSUE THREAD

**Issue by atline** [labgrid-project/labgrid#617]
I use something like next:

```
targets:
  main:
    resources:
      NetworkSerialPort:
        host: localhost
        port: 7003
        speed: 115200
    drivers:
      SerialDriver: {}
      UBootDriver:
        prompt: '=>'
        login_timeout: 120
```

After run `pyrest --lg-env local.yaml test_shell.py`, I could see case pass.

But, how I could get the output of the test? We need to show them to others, something like next:

```
U-Boot 2018.03-imx_v2018.03+g9a19c93 (Nov 04 2018 - 09:22:35 +0000)

CPU:   Freescale i.MX6Q rev1.2 at 792MHz
CPU:   Commercial temperature grade (0C to 95C) at 52C
Reset cause: POR
Model: Freescale i.MX6 Quad SABRE Smart Device Board
Board: MX6-SabreSD
DRAM:  1 GiB
PMIC: PFUZE100! DEV_ID=0x10 REV_ID=0x10
MMC:   FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
Loading Environment from MMC... *** Warning - bad CRC, using default environment

Failed (-5)
No panel detected: default to Hannstar-XGA
Display: Hannstar-XGA (1024x768)
In:    serial
Out:   serial
Err:   serial
switch to partitions #0, OK
mmc1 is current device
flash target is MMC:1
Net:
Warning: ethernet@02188000 using MAC address from ROM
eth0: ethernet@02188000 [PRIME]
Fastboot: Normal
Normal Boot
Hit any key to stop autoboot:  0
=> version
U-Boot 2018.03-imx_v2018.03+g9a19c93 (Nov 04 2018 - 09:22:35 +0000)

arm-poky-linux-gnueabi-gcc (GCC) 7.3.0
GNU ld (GNU Binutils) 2.30.0.20180208
=> print ethaddr
ethaddr=00:04:9f:02:55:93
=>
```

My case will try to input `version` etc command to command, how these outputs could be shown?
