### ISSUE TITLE
labgrid-exporter does not start ser2net

### ISSUE THREAD

**Issue by kjeldflarup** [labgrid-project/labgrid#761]
I'm moving from Scratch to Buster on my RPi units. Sametime I also loaded v0.3.2 (and v0.3.0)

I have this exporter yaml which I used to use with 0.1.0
```
pcm52:
  location: pcm52
  USBSerialPort:
    match:
      '@sys_name': '1-1.2'
  NetworkPowerPort:
    model: simplerest
    host: 'http://$LG_EXPORTERIP:9999/gpio/21/{value}'
    index: 0
  NetworkService:
    address: '172.29.5.42'
    username: 'root'
```

When I do a show on the exporter I get this
```
Matching resource 'USBSerialPort' (172.17.120.27/pcm52/NetworkSerialPort/USBSerialPort):
  {'acquired': None,
   'avail': True,
   'cls': 'NetworkSerialPort',
   'params': {'extra': {'path': '/dev/ttyUSB0',
                        'proxy': 'pi013.deif.com',
                        'proxy_required': False},
              'host': '172.17.120.27',
              'port': None,
              'speed': 115200}}
```

Because it has `/dev/ttyUSB0` it means that there is a match on `1-1.2`, but no port is assigned and `ser2net` is not running. 

Trying to debug `labgrid/remote/exporter.py`, I find that `class SerialPortExport` is initialized, but `_start` is never called. 

I can't figure out where in the code this `start()` should be called.
