### ISSUE TITLE
Bracketed-paste mode makes ShellDriver prompt detection fail

### ISSUE THREAD

**Issue by Fermi-4** [labgrid-project/labgrid#969]
I am following the getting starting steps and running the first test

I have local config file setup for my pi zerow:
```
targets:
  main:
    resources:
      RawSerialPort:
        port: "/dev/ttyUSB0"
    drivers:
      ManualPowerDriver:
        name: "example"
      SerialDriver: {}
      ShellDriver:
        prompt: 'pi@\w+:[^ ]+ '
        login_prompt: 'raspberrypi login: '
        username: 'pi'
        password: 'password'

```

I have verified the port `/dev/ttyUSB0` is correct using dmesg

When I run the test using: 
```
pytest --lg-env local.yaml test_shell.py
```
I consistently get this timeout  error: 
```
**ERROR test_shell.py::test_shell - pexpect.exceptions.TIMEOUT: Timeout of 4.93 seconds exceeded or connection closed by peer**
```
I also see this error in dmesg after test is run (bold):

[670927.706302] usb 1-7: new full-speed USB device number 72 using xhci_hcd
[670927.866892] usb 1-7: New USB device found, idVendor=067b, idProduct=2303, bcdDevice= 4.00
[670927.866900] usb 1-7: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[670927.866903] usb 1-7: Product: USB-Serial Controller
[670927.866906] usb 1-7: Manufacturer: Prolific Technology Inc.
[670927.869636] pl2303 1-7:1.0: pl2303 converter detected
[670927.871602] usb 1-7: pl2303 converter now attached to ttyUSB0
**[670972.423388] pl2303 ttyUSB0: pl2303_get_line_request - failed: -32
[670972.423787] pl2303 ttyUSB0: pl2303_get_line_request - failed: -32
[670980.558787] pl2303 ttyUSB0: error sending break = -32**

I am using the pl2303 to convert serial/usb

One last thing to note is that when the test is over and I minicom to the pi I can see that it did indeed login successfully:
```
pi@raspberrypi:~$ whoami
pi
```
